apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: notification
  labels:
    team: notificationteam
spec:
  selector:
    matchLabels:
      app: notification
  endpoints:
  - port: server